LachezaraLaz/341-soen341project2023

README.md
=> Update in README - Adding languages

README.md
Reverts LachezaraLaz/341-soen341project2023#24
=> Revert "Update in README - Adding languages"

README.md
Added the strengths for the people I had, added all usernames and tried to make it clearer
=> Update README file - adding username & strengths

README.md
Fixed some typos,  "developer" has one p only. Added Technical Lead as a role for Megan. Added Megan's strengths.
=> Update README.md - update Megan's strengths and roles, fix typos

README.md
added strengths under "Suha Abubakr"
=> Update README.md with Suha's strengths

README.md
The objective, project description, and core features sections have been drafted and added to the README.md file.
=> Update README.md - objective, description, features added

Feature 4 - Sign up - Login/Login-html file.html
added welcome message, email/password input, checkbox for remember me, submit button and links for forgot password and new to __ (not linked yet, to be done)
=> Update Login-html file - beginning

Feature 4 - Sign up - Login/Login-CSS file.css
seems to have a problem with other pull request
=> Update Login-CSS file

README.md
#3 Added the programming languages to the README.me file
=> Update README.md - added programming languages

login.py
I initially just committed the file from my vscode, but I was trying to make a pull request not just commit it directly, so here I am adding some slight change to the file so I can open a pull request for it.
This is my first draft for the login functionality it basically is nothing at all, just the beginning.
=> Adding login.py

Feature 4/Sign Up/Sign Up-html file.html
improved the navbar and footer, added function to see password and confirm password
=> Update sign up html - javascript

signup.py, templates/signUpHTML.html
establishes data flow from frontend to backend and allows user to signup to the service. [Fixes #53, #55 ]
=> Implements Signup

templates/profileHTML.html
adjusting profile picture mx height from 222px to 244px for better aesthetic appeal
=> Update profileHTML.html adjust pfp max height

signup.py, templates/jobDashboardHTML.html, templates/jobPostingHTML.html, templates/signUpHTML.html
implementing dynamic job postings and loading of jobs (job dashboard), verifies no such user in database before signup. fixes #69 #68
=> Dynamic Dashboard and User Verification before Signup

Implico/templates/editProfile.html, Implico/templates/profileTempHTML.html
#65 changes to the UI were made
=> User Profile Frontend Mods

Implico/userProfile.py
#66 User Profile Page now reads from database as well as Edit
=> Profile Page and Editing Page

Implico/__init__.py, Implico/adminJobPosting.py, Implico/notification.py
adding the python file and some base fiinctionality of adminJobPostings page. Fixed typos of notification python file, etc..
=> Adding adminJobPostings.py Inas-Branch

Implico/notification.py, Implico/templates/JobDescription.html, Implico/templates/Notification.HTML
when apply button is clicked, it adds necessary information in database. this is ONLY for student. what is now left is to display information in the notification page.
=> Added most of backend notification

Implico/notification.py
necessary information is retrieved from database, only thing missing is displaying information in the html file
=> additional code and comments for notification

Implico/notification.py, Implico/signup.py, Implico/templates/JobDescription.html, Implico/templates/viewJobPosting.html
viewing the job posting for a candidate is completely done
=> Viewing the job posting for a candidate

Implico/notification.py, Implico/templates/Notification.HTML
some further changes for the right person to get the notification
=> further change for notification

Implico/projectDatabase.py
change a column name and reference in notification table in database
=> change a column name and reference in notification

Implico/notification.py, Implico/templates/Notification.HTML
notification from student to employer is completely done. employer to student is next but waiting for finalizations from suha
=> notification from student to employer

Implico/templates/adminJobDashboard.html, Implico/templates/editJobAdmin.html
frontend modifications to fit the requirements of issue #101
=> #101 modifications to frontend of these admin pages were made

Implico/templates/JobDescription.html, Implico/templates/adminJobDashboard.html, Implico/templates/editJobAdmin.html, Implico/templates/editJobEmployer.html, Implico/templates/jobDashboardHTML.html, Implico/templates/viewJobPosting.html, Implico/templates/viewMoreJobEmployer.html
Fixing search bar for job search and adding frontend implementation for tags
Closes #142
Closes #143
=> Add frontend implementation of Tags and fix search bar for job search

Implico/notification.py, Implico/templates/JobDescription.html
Inserting information in jobAppiclants table when candidate applies
=> Inserting information in jobAppiclants table

Implico/static/css/signUpCSS.css, Implico/templates/loginHTML.html, Implico/templates/profileTempHTML.html, Implico/templates/signUpHTML.html
Removed the footer from signup and login pages, fixed css for userType selection in signUp html page, fixed icons in profile page
=> Small changes on HTML files

Implico/templates/profileTempHTML.html
=> Fixing css for profile page
